### ISSUE TITLE
Toggling a feature layer on/off quickly causes the visible portion of the layer to remain on the map

### ISSUE THREAD

**Issue by bsnider** [Esri/esri-leaflet#691] opened 2015-12-10 01:14 UTC
See this sample: http://jsfiddle.net/nbn1vgd8/4/

1. Quickly click the addLayer/removeLayer button twice.
2. Zoom out.
3. Note that the layer should be totally removed from the map, but some counties still display.
4. Contrast this with this sample using geojson: http://jsfiddle.net/z3nmxrp3/

**Comment by jgravois** [comment] 2015-12-16 20:12
this issue [isn't reproducible](http://jsfiddle.net/m976m4wa/) in Leaflet 1.0.0-beta.2 / Esri Leaflet 2.0.0-beta.6, but the repro case does result in a nasty uncaught console error.

![screenshot 2015-12-16 12 05 37](https://cloud.githubusercontent.com/assets/3011734/11852673/2493d008-a3ee-11e5-9dc8-246350250148.png)

this is because internally in the API we call [`FeatureManager._map.getZoom()`](https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L150-L153) after the layer has already been removed from the map (and its corresponding private property unset).
```js
var zoom = this._map.getZoom(); // this._map is undefined
```
do any brave souls want to venture a guess as to how we could handle this situation more elegantly?

**Comment by patrickarlt** [comment] 2015-12-25 21:02
@jgravois I'll take a look at this.

**Comment by patrickarlt** [comment] 2015-12-26 00:22
@jgravois looks like this is a pre 2.0 issue. Maybe it is related to https://github.com/Esri/esri-leaflet/pull/632?

**Comment by jgravois** [comment] 2015-12-30 19:16
based on changes introduced in #695, the problem i noted in my first reply within this thread is now completely resolved in `master`.

i'll leave this issue open in case we decide to backport a fix to `1.0.x`

**Comment by patrickarlt** [comment] 2015-12-31 00:37
@jgravois any chance you could backport to `1.0.x`? It is a verified bug and we did promise to fix bugs.

**Comment by jgravois** [comment] 2016-01-02 00:16
the fix is [live](http://jsfiddle.net/nbn1vgd8/9/) in `1.0.2`.  let me know if you have any questions @bsnider.

**Closed by jgravois** 2016-01-02 00:16 UTC
