### ISSUE TITLE
ImageMapLayer "noData" option must be entered as string in order to work.

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#946] opened 2017-04-11 22:36 UTC
Run an imageService of your choice and set noData as described in the api:
```
	myService = L.esri.imageMapLayer({
		url : 'https://myService/ImageServer',
		noData: 0,
		noDataInterpretation:'esriNoDataMatchAny',
	});
```

In my case, all of my noData showed up anyways. I could fix this by changing my option to this:

`noData:'0',`

**Comment by jgravois** [comment] 2017-04-11 23:38
thanks for the report. this is happening because `0` is falsy when we check to see if the param has been set at all.

```js
// https://github.com/Esri/esri-leaflet/blob/43d8e8d6302440b001475d940f83b54da5d1be76/src/Layers/ImageMapLayer.js#L168
if (this.options.noData) {
    params.noData = this.options.noData;
}
```
i'll make time to fix soon.

**Comment by jgravois** [comment] 2017-04-24 18:58
the problem is now resolved in `master`. thanks for taking the time to report it!

**Closed** 2017-04-24 18:57 UTC
Labels: Bug, Help Wanted, Small Fix
