### ISSUE TITLE
not able to step through sourcemapped breakpoints

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet#712] opened 2015-12-31 00:55 UTC
is everyone else unable to set/hit breakpoints in the source mapped API code that is now transpiled from ES6?

i know i used to, but now i get no breakpoints at all in Chrome `47.0.2526` or Firebug `33.0.2` and the breakpoints i get in Safari `9.0.2` are completely screwed up.

doesn't matter whether i'm using `http-server` or a 'real' web server.
happening on two different computers...

**Comment by rowanwins** [comment] 2016-01-06 22:59
Gday @jgravois I tried to take a look at this but I discovered that the current npm install isn't working on  windows. I'm having a little bit of trouble working out what exactly is breaking, it looks like something to do with karma.... I'll try to do some digging and see if I can actually report anything useful :)

Cheers

**Comment by rowanwins** [comment] 2016-01-07 00:31
Ok so I've narrowed things down to the build script and it seems to be failing in the use of rollup, I get `[TypeError: Cannot read property '0' of null]`

There is a [similar issue](https://github.com/rollup/rollup/issues/119) in the rollup repo which seems to relate to windows and filepaths. I've previously run into issues with node and windows filepaths and have used the [filepath module](https://www.npmjs.com/package/filepath) to get around things so I'll see if I can have a bit more of a play and get anywhere...

Cheers

**Comment by jgravois** [comment] 2016-01-07 19:40
thanks @rowanwins.  can you log a new issue if you are seeing problems when running `npm install esri-leaflet@2.0.0-beta.7`on windows so we can make sure to get them sorted out?

**Comment by rowanwins** [comment] 2016-01-10 22:13
Ok so back to the breakpoint issue, yep Im having this happen as well. In chrome I seem to be seeing the source mapped files but breakpoints aren't being hit

![Files shown](https://www.dropbox.com/s/cxqlpzjr6lfbrzv/files.jpg?dl=1)

**Comment by patrickarlt** [comment] 2016-01-17 16:25
I'm wondering if this is just a result of how I am building the source maps with rollup + uglifyjs. The best thing to do would probally be to upgrade to the latest version of Rollup with the uglifyjs plugin rather then do it by hand.

If that doesn't fix anything then this needs deeper investigation.

**Comment by rowanwins** [comment] 2016-01-18 04:03
Ok so I've just upgraded uglify-js to v2.6.1 (the latest) and that seems to work in generating correctly working source mapped files. 

Updating rollup to the latest seems to cause some issues 
````
Treating 'arcgis-to-geojson-utils' as external dependency
Treating 'leaflet-virtual-grid' as external dependency
Treating 'tiny-binary-search' as external dependency
No name was provided for external module 'leaflet' in options.globals – guessing 'L'
No name was provided for external module 'arcgis-to-geojson-utils' in options.globals – guessing 'GeojsonUtil'
No name was provided for external module 'leaflet-virtual-grid' in options.globals – guessing 'VirtualGrid'
No name was provided for external module 'tiny-binary-search' in options.globals – guessing 'BinarySearchIndex'
````

So to confirm my config which is working with source mapped files
````
    "rollup": "^0.19.0",
    "uglify-js": "2.6.1",
````

Cheers
Rowan

**Comment by patrickarlt** [comment] 2016-01-18 22:14
@rowanwins I still can't seem to hit these breakpoints in Chrome. Firefox works fine and my config has has had `uglify@2.6.1` from the start.

The best I have been able to achieve is to update to `rollup@0.24.x` which requires some changes and not to uglify. This produces an uncompressed file which works in both Chrome and Firefox. If I minify the file trying to set a breakpoint actually sets a breakpoint in the wrong place.

**Comment by rowanwins** [comment] 2016-01-18 22:26
I'm chalking this down as the first win for windows in the epic windows vs mac battle :)

I've been testing in chrome (Version 47.0.2526.111) with no worries and firefox also seems to work fine.

**Comment by patrickarlt** [comment] 2016-01-19 01:51
Chrome has a quite a few issues with souremaps and breakpoints that might explain this. Given that I can only reproduce in Chrome on a Mac I'm closing this.

* https://code.google.com/p/chromium/issues/detail?id=451015
* https://code.google.com/p/chromium/issues/detail?id=459499
* https://code.google.com/p/chromium/issues/detail?id=270917

**Comment by jgravois** [comment] 2016-01-19 19:24
@patrickarlt can you share a code snippet of the changes you had to make to bump rollup to `0.24.x` (or submit a PR) please?  right now i still can't debug anywhere.

**Comment by patrickarlt** [comment] 2016-01-19 20:46
@jgravois I'm going to do it as part of https://github.com/Esri/esri-leaflet/issues/733. There isn't point in overhauling the process in one repo when I really want to upgrade it everywhere.

**Closed by patrickarlt** 2016-01-19 20:46 UTC
