### ISSUE TITLE
Issue with L.esri where esri is undefined.  (Question)

### ISSUE THREAD

**Issue by rnonajr** [Esri/esri-leaflet#1113] opened 2018-07-18 15:56 UTC
Hi,

I've never worked with esri and right now I'm taking over a project using esri and I am encountering an issue that doesn't always occur.  

Sometimes when a user attempts to open a map, the map area remains grey and in the console I can see the error message "Cannot read property 'featureLayer' of undefined" 

```js
map = L.map("map").setView(JSON.parse(result.CenterOfTheMap), result.ZoomLevel);
 
           var zipcodes = L.esri.featureLayer({
                url: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_ZIP_Codes/FeatureServer/0',
                zoom: 18,
                simplifyFactor: 0.35,
                precision: 5,
                fields: ['FID', 'ZIP', 'PO_NAME'],
                style: function (feature) {
                    if (DoesItExists(feature.properties.ZIP)) {
                        return {
                            color: getBorderColor(feature.properties.ZIP), //'#A9A9A9',
                            weight: 1,
                            fillOpacity: 0.7,
                            fillColor: getColor(feature.properties.ZIP)
                        }
                    }
                    else {
                        return {
                            color: '#A9A9A9',
                            weight: 0.2
                        }
                    }
                }
            }).addTo(map);
```

When I Watch the L variable it is defined but L.esri is undefined.

As I said, this issue doesn't always manifest itself and I'm not sure what / where I should be looking for a solution.  Any help would be appreciated.

Thanks
Bob

**Comment by jgravois** [comment] 2018-07-18 16:43
How exactly are you loading Leaflet (and our own plugin) in your application?
when `L.esri` is undefined, its likely that the source code for the plugin failed to load entirely for some reason.

**Comment by rnonajr** [comment] 2018-07-18 17:00
The code loads leaflet in the cshtml page

`

link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
script  src="https://unpkg.com/leaflet@1.0.3/dist/leaflet-src.js"></script>


script src="https://unpkg.com/esri-leaflet@2.0.7"></script>
script src="https://unpkg.com/esri-leaflet@2.0.7"></script>

<script type="text/javascript">

    var filtersSelAfterDlgOpen = new Array();
    var invalidZipCode = false;
    var minZip;
    var maxZip;
    var dlgOrgHtml;
    var showHouseholdPercentage = false;
    var custombounds = new Array();
    var selectedMapLayerIDs = new Array();
    var totalZip = new Array();
    var model = $.parseJSON("@(Html.Raw(Json.Encode(@Model)))");
    debugger;
    var orgmodel = $.parseJSON("@(Html.Raw(Json.Encode(@Model)))");
    function ToggleShowHouseHold(ctrl) {
        alert($(ctrl).attr("checked"));
    }

    resize();

    $(document).ready(function () {
        document.getElementById("pnlDistributionMap").style.display = "";
        //set name
        $("#txtMapName").val(orgmodel.InputQuery.NameOfMap);
        //resize();
        $(window).on("resize", function () {
            $("#map").height($("#mapcontainer").height()).width($("#mapcontainer").width());
            $('#map').css("margin-bottom", 50);
            //map.invalidateSize();
        }).trigger("resize");

        debugger;
        if ((model.InputQuery != null) && (model.InputQuery.SelectedMapLayerIDs != null)) {
            selectedMapLayerIDs = model.InputQuery.SelectedMapLayerIDs.split(",");
        }
        
        Send();
        //hide all intially
        $(".filter_sec").hide();
        $("#info-pane").hide();`

**Comment by rnonajr** [comment] 2018-07-18 17:00
**and the code to L.esri.featureLayer is in a Javascript file and is called by the Send() function in the above Document.Ready function.**

`          map.off();
            map.remove();

            map = L.map("map").setView(JSON.parse(result.CenterOfTheMap), result.ZoomLevel);

            var zipcodes = L.esri.featureLayer({
                url: "https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_ZIP_Codes/FeatureServer/0",
                zoom: 18,
                simplifyFactor: 0.35,
                precision: 5,
                fields: ["FID", "ZIP", "PO_NAME"],
                style: function (feature) {
                    if (DoesItExists(feature.properties.ZIP)) {
                        return {
                            color: getBorderColor(feature.properties.ZIP), 
                            weight: 1,
                            fillOpacity: 0.7,
                            fillColor: getColor(feature.properties.ZIP)
                        }
                    }
                    else {
                        return {
                            color: "#A9A9A9",
                            weight: 0.2
                        }
                    }
                }
            }).addTo(map);

            L.esri.basemapLayer("Topographic").addTo(map);
       `

**Comment by rnonajr** [comment] 2018-07-18 17:08
Sorry I had to remove < from the script tags otherwise it was putting the actual script file in there.  The tags are set up properly in the code.

**Comment by jgravois** [comment] 2018-07-18 17:16
this smells like a duplicate of #1096.

please try either using a different CDN to host esri-leaflet or shipping it alongside your app and see if that resolves the problem.

**Comment by rnonajr** [comment] 2018-07-18 17:18
OK, I'll take a look at that.  Thanks!

**Comment by rnonajr** [comment] 2018-07-18 19:15
How do I go about shipping it with my app?  I mean, where do I go to download the files (which is what I'm assuming you mean).

**Comment by rnonajr** [comment] 2018-07-18 19:15
I tried an different CDN to host and got the same issue.

**Comment by jgravois** [comment] 2018-07-18 19:50
> where do I go to download the files..

the files you'd host are the same exact files you are currently referencing via CDN.

is your app public? if so what is the url?
if not, you'll need to snoop the web traffic when your app loads to confirm manually that the leaflet source code is retrieved successfully and that the esri-leaflet source code is retrieved successfully immediately afterward.

**Comment by rnonajr** [comment] 2018-07-18 19:56
Currently it's in a testing environment behind a firewall.

Sorry but this project was dumped on me after it was taken away from a 3rd party firm.  So please forgive me for what might be ignorant questions.

For the files I'd host, I understand that they are the ones that are being referenced but where do I get that file so that I may include it in my project or am I missing what you're saying when you say Host?

Thanks
Bob

**Comment by jgravois** [comment] 2018-07-18 20:07
it may just be a typo, but in the code snippet you shared you're loading esri-leaflet twice when you should only be loading it once.

```html
<!-- Load Esri Leaflet from CDN -->
<script src="https://unpkg.com/esri-leaflet@2.0.7"></script>
<script src="https://unpkg.com/esri-leaflet@2.0.7"></script>
```
should be
```html
<!-- Load Esri Leaflet from CDN -->
<script src="https://unpkg.com/esri-leaflet@2.0.7"></script>
```

to host that file yourself, one option would be to just load https://unpkg.com/esri-leaflet@2.0.7 in its own browser tab and do a <kbd>saveAs</kbd>.

**Comment by rnonajr** [comment] 2018-07-18 20:09
I did remove the 2nd load. I noticed that when I was trying a different CDN.  

Thanks, I'll do the save as on the css and js files and add them to the project and reference them and try it that way.

Thanks again!
Bob

**Closed** 2018-07-21 18:06 UTC

**Comment by bouyeijiang** [comment] 2025-11-17 03:47
import * as L from 'leaflet'; // "^1.9.4",
import 'esri-leaflet'; // "^3.0.19",
 
L.esri undefined
