### ISSUE TITLE
Support for FeatureLayers in non-mercator projections

### ISSUE THREAD

**Issue by steveoh** [Esri/esri-leaflet#483] opened 2015-03-16 23:41 UTC
When using non wgs84 projections with a feature layer, the `bounds` argument passed to query to gather features is wonk.

This causes overlapping query bounds and the number of requests is much larger than it should be. This could bump you up against the max open socket per url setting and is just bad. 

Let's use this as a spot to track leaflet 1.0 and proj4leaflet as they mature and see how this all shakes out.

What we expected

![image](https://camo.githubusercontent.com/eda28444ec72a7f9110df29916f20d50fd1ec683/68747470733a2f2f7261772e6769746875622e636f6d2f7061747269636b61726c742f6c6561666c65742d7669727475616c2d677269642f6d61737465722f6578616d706c652e6a7067)

what we get 

![image](https://cloud.githubusercontent.com/assets/325813/6678714/99369760-cc03-11e4-84c7-3dded8b297c6.png)

**Comment by patrickarlt** [comment] 2015-03-17 00:17
Some background on this.

At some point in the past `L.GridLayer` was split into `L.GridLayer` (with DOM) and `L.Grid` (no DOM) ultimately this was deemed to cumbersome (it was) and was abandoned.

At some point I took the `L.Grid` code and transformed it into [`L.VirtualGrid`](https://github.com/patrickarlt/leaflet-virtual-grid) which is used inside of Esri Leaflet. I think was BEFORE the major CRS refactor.

I'm betting that I just need to update `VirtualGrid` to the new code to fix this.

**Comment by patrickarlt** [comment] 2015-03-19 20:46
@steveoh I took a look at this today using the latest Leaflet and Proj4Leaflet code. The result is still pretty much the same. I created a repo https://github.com/patrickarlt/virtual-grid-debug if you want to pull it down and play with it.

I'm wondering if @steveoh  or @stdavis (or anyone who understands projections better then I do) could look at https://github.com/patrickarlt/virtual-grid-debug/blob/master/virtual-grid.js#L174 I think the problem is occurring somewhere around there. At that point in the code the projected coords `nwPoint` and `sePoint` are in the projected coordinates and `nw` and `se` are WGS84. Since ArcIGS Server will do all the projection server side I wonder if everything is actually fine since we are pass the NE and SW points in WGS84 (extent/envelope) and the server knows what to do with them projecting into the local projection (Utah) and back out again in WGS 84. So I don't think we are actually missing features and the grid still works. Its just that drawing the vector grid (properly projected) makes it look like it isn't.

Do you think think this is correct?

**Comment by patrickarlt** [comment] 2015-03-19 20:50
![non-mercator_projection](https://cloud.githubusercontent.com/assets/378557/6740643/dfd93884-ce3e-11e4-95a9-f6083d8ca59f.png)

**Comment by stdavis** [comment] 2015-03-23 19:20
Took a look at this. Couldn't make much sense of it. But yes, ArcGIS Server should be able to handle sending it different coordinate systems.

**Comment by w8r** [comment] 2015-03-23 20:06
I also think the grid doesn't lose the features, but in addition to that, we have a problem with local projections:
[jsFiddle](http://jsfiddle.net/w8r/g9h8yf4g/): 
cellBounds in the method creating tile coverage are broken by this https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureGrid.js#L119 code, it kind of assumes `_originalTopLeftPoint` to have positive values(which can be wrong in case of bounded projections, as far as I understand)
I'm trying to figure out how to deal with that

**Comment by w8r** [comment] 2015-03-23 20:08
JsFiddle contains only an example of projection(Qatar Nahrwan 1967), no feature layer, cause in that case it tries to request ~20000 virtual tiles after having dropped the topLeftPoint value while calculating the viewport tile coverage.

**Comment by patrickarlt** [comment] 2015-03-24 03:55
@w8r There are a whole bunch of projections issues in Leaflet 0.7.3. You can see a summary of some of them in https://github.com/Leaflet/Leaflet/issues/2239 and https://github.com/Leaflet/Leaflet/pull/2247. A lot of this SHOULD be resolved in Leaflet 1.0. I'll see if I can get your example working in 1.0, but it would probably be worth filing an issue with Proj4Leaflet since this isn't a specific issue with Esri Leaflet.

Do you have a tile set and feature layer for that projection? It would be helpful to debug in something other then Utah state plane.

**Comment by w8r** [comment] 2015-03-24 09:32
@patrickarlt, Leaflet 1.0 will break a lot of plugin and their deps, so it's a long run.
The reason I filed the issue here is I don't really thing there's something wrong with having `_initialTopLeftPoint` with negative values. I'll try and check the math there
About the data and tileset, well yes and no, I have some data and I'm using it via WMS, but it's commercial, I can't put it online. I'll try and find something that at least shows the coastline and depth levels there

**Comment by w8r** [comment] 2015-03-24 12:06
Found a service with some data at this location, updated http://jsfiddle.net/w8r/g9h8yf4g/, it's marine zones in the region

**Comment by w8r** [comment] 2015-03-24 12:16
there's a feature service in that area

http://services1.arcgis.com/zu8dBGfmKCvrZHh2/arcgis/rest/services/Buffer%20of%20Dubai,%20Dubai,%20United%20Arab%20Emirates%20-%20Doha,%20Ad%20Daw%E1%B8%A9ah,%20Qatar_Route/FeatureServer/0

**Comment by patrickarlt** [comment] 2015-10-28 04:37
I'm going to close this in favor of a new issue to audit all the spatial reference work for all layer types.

**Closed by patrickarlt** 2015-10-28 04:37 UTC
Labels: 1.0

**Comment by patrickarlt** [comment] 2015-11-06 05:49
This will work in the next version! There are still some issues with Stereoscopic projections (Alaska, polar, ect...) but generally work very well.

**Comment by w8r** [comment] 2015-11-06 10:54
:+1:
