### ISSUE TITLE
Vector Tile Plugin: Tile Rendering Issues

### ISSUE THREAD

**Issue by jonahadkins** [Esri/esri-leaflet#1016] opened 2017-10-25 12:25 UTC
* Browser and version: Chrome 61
* Version of Leaflet: `1.2, CDN`
* Version of esri Leaflet: `2.1, CDN`

Steps to reproduce the error:

1. Add a `L.esri.Vector.layer` like `L.esri.Vector.layer('5e61d5243ea7454784edb8f89c819834').addTo(map);

What happens is: my tiles do not render, devtools shows 404 errors accessing the tile service pbf's

I've tried other layer id's like these that gave similar results.
- 359ba7cfa9b4c19954a282a515238de
- 4fa0638d234c47ff925e4f818868c14a

However these one worked
- c7ee7e11400e420d8ccef79ac4986f48
- af685057fc6a495790760d3fbd4c9c11

Which makes me think the issue is related to the tilemap/LOD's?

Thanks!

**Comment by jgravois** [comment] 2018-01-19 19:49
duplicate of https://github.com/Esri/esri-leaflet-vector/issues/37.

wish i had some ideas to actually _fix_ the problem.

**Closed by jgravois** 2018-01-19 19:49 UTC
