### ISSUE TITLE
Url splice error when url contains params(featurelayer,dynamicMapLayer,tilelayer)

### ISSUE THREAD

**Issue by westfalenxqq** [Esri/esri-leaflet#1030] opened 2017-12-05 08:55 UTC
* Browser and version:

 Chrome 

* Version of Leaflet (`L.version`):

1.0.0

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.0

Steps to reproduce the error:

1. add featureLayer by this way
```
 L.esri.featureLayer({
         url: 'http://192.168.11.218:6080/arcgis/rest/services/CQboundary/MapServer/0?isPlatform=true'          
 }).addTo(map);
```
2. then check the url request
![image](https://user-images.githubusercontent.com/8254415/33598093-76a9c368-d9dc-11e7-9a99-fb68e047da87.png)
**the url splice error**
I was expecting
![image](https://user-images.githubusercontent.com/8254415/33598156-adb74204-d9dc-11e7-8d8f-5070ccfff8f7.png)

**Test Code**
```js
var map = L.map('map').setView([37.71, -99.88], 4);

  L.esri.basemapLayer('Gray').addTo(map);

  L.esri.dynamicMapLayer({
    url: 'https://services.arcgisonline.com/arcgis/rest/services/Specialty/Soil_Survey_Map/MapServer?param=1',
    opacity: 0.7
  }).addTo(map);
```

**Comment by jgravois** [comment] 2017-12-05 17:41
this is more or less a duplicate of #979. i definitely see the value in allowing developers to pass through their own custom parameters.

**Closed** 2017-12-05 21:45 UTC

**Comment by westfalenxqq** [comment] 2017-12-06 12:17
thank you
