### ISSUE TITLE
'Access-Control-Allow-Origin' issue is raised when I call admin layers form Arcgis Server. My application has built on Leaflets and Geoserver. Need help , it is urgent.

### ISSUE THREAD

**Issue by mercy-monica** [Esri/esri-leaflet#1116] opened 2018-07-30 07:40 UTC
* Browser and version:

ie: Chrome 51, IE11

* Version of Leaflet (`L.version`):

0.7.7, 1.0.0?

* Version of esri Leaflet (`L.esri.VERSION`):

1.0.4, 2.0.3, `master`?

Steps to reproduce the error:

1. first do this
2. then do this

What happens is [X].

I was expecting [Y].

(if possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem)

* Optional: I'm *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), I'm loading/bundling the library using:

[webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/)?

**Comment by jgravois** [comment] 2018-07-30 15:14
my best guess is that you are encountering an error because the specific service you're trying to load using esri leaflet doesn't support CORS.

see https://github.com/Esri/esri-leaflet-doc/issues/79 for more information.

without you taking the time to identify the versions of Leaflet and Esri Leaflet you're using and sharing either a live reproducible test case or code snippet, there's not much additional assistance i can provide.

**Comment by jgravois** [comment] 2018-07-30 15:17
closing as a duplicate of https://gis.stackexchange.com/questions/291084/cors-issue-in-leaflet-using-arcgis-server

**Closed by jgravois** 2018-07-30 15:17 UTC
