### ISSUE TITLE
Error consuming secure map service that uses Windows Authentication

### ISSUE THREAD

**Issue by jgermain** [Esri/esri-leaflet#381] opened 2014-10-21 17:19 UTC
In Google Chrome browser, consuming a secure dynamic map service from an ArcGIS Server that uses integrated Windows Authentication fails to challenge user for credentials. This works correctly in IE11, Firefox and Safari.

Sample code attached.
![Uploading windowsauth.html . . .]()

**Comment by jgravois** [comment] 2015-02-19 17:14
as we weren't able to repro.  closing now.  happy to investigate further if more info can be provided.

**Comment by jmfolds** [comment] 2015-02-19 19:36
Here is an example of the issue on codepen: http://codepen.io/jmfolds/pen/ZYxRdN
No prompt for creds in Google Chrome (401 in console), but IE and Firefox are prompting as expected.

**Comment by jgravois** [comment] 2015-02-19 20:21
thanks so much @jmfolds.  i just confirmed that the same problem isn't evident in the JSAPI.  strangely, i can get the dialog to display in chrome just fine by calling
```
L.esri.dynamicMapLayer('http://odot.dtsagile.com/agsadmin/rest/services/SecuredServices/SecureLayers/MapServer', {useCors: false}).metadata();
```
at first i thought the problem would be resolved for you as well after setting `useCors: false` in your own snippet, but the challenge is still suppressed for some reason...

**Comment by jmfolds** [comment] 2015-02-19 20:32
@jgravois No problem, thanks for looking into this.

**Comment by patrickarlt** [comment] 2015-04-25 02:49
@jgravois @jmfolds any luck on this?

**Comment by jgravois** [comment] 2015-04-25 15:15
@patrickarlt I was able to reproduce this error inconsistently.  would you be up for taking a look at it together in redlands sometime?

**Comment by jmfolds** [comment] 2015-04-28 22:26
I have not had time to investigate much further on this, unfortunately. We are currently using a workaround similar to what @jgravois mentioned:
```L.esri.dynamicMapLayer('http://odot.dtsagile.com/agsadmin/rest/services/SecuredServices/SecureLayers/MapServer', {useCors: false}).metadata();```

When calling .metadata(), the dialogue pops in Chrome. We are making a request to the service for legend info, which forces the credential dialogue in Chrome also.

**Comment by patrickarlt** [comment] 2015-04-28 22:51
@jmfolds Given what your workaround is I think I know whats happening. Esri Leaflet does not automatically request service metadata when a layer is created, unlike the JS API. If that metadata request (or any request) is what is triggers the authentication challenge then you could also probably do.

```js
L.esri.dynamicMapLayer('http://odot.dtsagile.com/agsadmin/rest/services/SecuredServices/SecureLayers/MapServer', {
  f:'json', // requests JSON that has the URL to the map image in it.
  useCors: false // this is probably only needed if the service is on a sever before 10.1
});
```

I was really confused about this whole issue in general until I realized that this is just HTTP Basic Auth! The reason you never saw the challenge in Chrome is chrome doesn't challenge for basic auth on images http://stackoverflow.com/questions/19244006/chrome-basic-auth-image-requests-return-401-but-not-when-called-directly as a security tradeoff.

So here is what was happening in Esri Leaflet:

1. Init `L.esri.dynamicMapLayer`
2. Make request for image.
3. All browsers except Chrome will throw a challenge

And the JS API

1. Init your dynamic map layer
2. Dynamic map layer requests its metadata
3. Challenge
4. Request for image starts

The code I gave you above makes Esri Leaflet make a JSON request for all the images which SHOULD trigger the challenge just like calling the `metadata()` method. Can you give that a shot?

**Comment by jmfolds** [comment] 2015-04-28 23:25
@patrickarlt Right on! I just tested this and it appears to fix the issue in Chrome. Here is a pen of it:

http://codepen.io/jmfolds/pen/gpbydL

Thanks for the help!

**Closed** 2015-04-29 16:57 UTC
