### ISSUE TITLE
v2.0.1: tile layer not shown any more, but instead a GET request to a strange URL happens

### ISSUE THREAD

**Issue by wasinger** [Esri/esri-leaflet#808] opened 2016-07-28 10:19 UTC
* Browser and version:

Firefox 47

* Version of Leaflet (`L.version`):

1.0.0-rc.2

* Version of esri Leaflet (`L.esri.VERSION`):

2.0.1

After Upgrading esri.Leaflet from 2.0.0 to 2.0.1, our tile layers (from our own arcgis server) are not shown any more, but instead a strange GET request to a non-existant URL that begins with path "undefined" relative to the root of our webapp is being sent that contains the whole service description of our tile layer service as query parameters, the request URL looks like this and is very, very long:

http://our.webserver/path_to_webapp/undefined?currentVersion=10.4&serviceDescription=...&mapName=Layer&description=&copyrightText=...&supportsDynamicLayers=false&layers=...

The request is being answered with a "414 Request-URI Too Large" status code by our web server (nginx).

The tile layer not being shown is initialized like this:

```javascript
layer_karte = esri.tiledMapLayer({
	    url: '//our.arcgis.server/arcgis/rest/services/Basiskarten/Stadtkarte/MapServer',
            minZoom: 12,
            maxZoom: 19,
            'detectRetina': false
        }).addTo(map);
```

Switching esri.leaflet back to version 2.0.0 all works like it should be: The tile layer is shown, and no strange request is being sent.

I guess esri.leaflet tries to fetch some meta information about the service (although it already has the complete service description, otherwise it could not be sent in the query string of the request) and some base url is missing (that's why the "undefined").

Any ideas what's happening and how this can be fixed?

**Comment by jgravois** [comment] 2016-07-28 17:14
the problem you describe is not reproducible in our samples
http://esri.github.io/esri-leaflet/examples/tile-layer-1.html

**Comment by jgravois** [comment] 2016-08-24 20:14
closing since @wasinger never wrote back, but more than happy to reopen and investigate further if anyone can reproduce the error and share a little more information.

**Closed by jgravois** 2016-08-24 20:14 UTC
