### ISSUE TITLE
ERR_NAME_RESOLUTION issue occuring with esri-leaflet attribution url 

### ISSUE THREAD

**Issue by vamsiampolu** [Esri/esri-leaflet#769] opened 2016-04-19 12:50 UTC
* Browser and version:

ie: Chrome 49

* Version of Leaflet (`L.version`):

0.7.3
* Version of esri Leaflet (`L.esri.VERSION`):

1.0.2

* I'm loading the library using script tag.

Steps to reproduce the error:

What happens is when I load the web page, I sometimes see an ERR_NAME_RESOLUTION error for 

https://static.arcgis.com/attribution/World_Topo_Map?callback=window._EsriLeafletCallbacks.c2&f=json

**Comment by jgravois** [comment] 2016-04-19 15:11
is there a specific place in the world (and zoom level) I can center a map to reproduce this problem?

it sounds like a problem with the attribution service itself, but if i can reproduce the error i'm sure we can trap it so that it doesn't bubble up to client applications.

**Comment by vamsiampolu** [comment] 2016-04-21 01:20
We open the map over Australia with the bounds(ad-hoc representation below):

```
{
  northEast: {
     latitude:-34.25267611710151,
     longitude:158.81835937499997
  },
  southWest: {
      latitude: -38.668356101515066,
      longitude:129.13330078125
  }
}
```

We open it at the zoom level `6`, the issue only appears sometimes at this zoom level and at other times at different zoom levels, the most we zoom into is about `16`.

**Comment by jgravois** [comment] 2016-07-06 21:52
i finally got around to looking at this today and i wasn't able to reproduce the reported error.  that said, i *could* generate a similar problem by substituting an invalid url in the esri-leaflet source.

![screenshot 2016-07-06 14 37 39](https://cloud.githubusercontent.com/assets/3011734/16635433/43eb3624-4387-11e6-906d-77dd9189333f.png)

as i expected, the error that appears in the console isn't something that we can supress in our code.  it is a message directly pertaining to the web traffic indicating that your ISP/reverse-proxy is under the impression that the resource you are attempting to fetch is temporarily unavailable.

it **is** possible that the web server hosting our static attribution content is failing to respond intermittently, but i also saw some instructions online indicating that [flushing DNS](https://www.wiknix.com/err_name_resolution_failed-error-solved/) can also resolve local errors in Chrome.
___

since there's nothing esri-leaflet can do here, i'm going to go ahead and close this ticket and hope that you've already begun to see consistent responses from the static attribution server.

if you continue to encounter errors, and flushing your DNS doesn't improve the situation, **please** feel free to write back again and i will forward on the message to the appropriate team.
___
postscript:
it doesn't appear to make the slightest difference what the intial extent of the map is when an application loads, because the attribution fetched from the web server is ***static*** (which explains the chosen subdomain).

**Closed by jgravois** 2016-07-06 21:52 UTC
Labels: Needs Review
