### ISSUE TITLE
Question: 'Map data not available' text is shown on grey layout

### ISSUE THREAD

**Issue by IvannaBabchanik** [Esri/esri-leaflet#1043] opened 2018-01-26 14:29 UTC
Hello, 
I'm observing 'Map data not available' text on grey layout  when 'noWrap' option is enabled and zoom level is 0 .

Step to reproduce:
1. Create map with esri layer and  'noWrap: true' option. The height of map container is 800px.
2. Do zoom out to minim zoom.
Observed: small map picture and grey layout around with text 'Map data not available'.
Expected: grey layout without text.

Is it possible to remove text from layout?  

Environment:
angular 5,  esri-leaflet 2.1.1

**Comment by jgravois** [comment] 2018-01-26 17:07
hello!

i can't reproduce the behavior you describe with a hosted `basemapLayer` or a custom `tiledMapLayer`.

http://jsbin.com/husabay/edit?html,output

happy to provide assistance if you can provide additional information.

**Comment by jgravois** [comment] 2018-01-31 01:37
thanks for the clarification. there are only 4 actual tiles at zoom level 0, so any requests that end in a number greater than `1` or less than `0` return the placeholder tile.

examples:
[../MapServer/tile/1/0/-1](http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/1/0/-1)
[../MapServer/tile/1/1/-1](http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/1/1/-1)
[../MapServer/tile/1/0/2](http://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/1/0/2)
[../MapServer/tile/1/1/2](http://services.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/1/1/2)

if you're working with a `tiledMapLayer` and you can get in touch with the person that administers the services, its actually possible to substitute a blank `.png` as the generic placeholder tile ([reference](https://support.esri.com/en/technical-article/000010678)).

if you're really consuming an Esri hosted basemap, you don't have that option, but you might try overriding/inserting a little additional logic into [`TileLayer.getTileUrl()`](https://github.com/Leaflet/Leaflet/blob/3e8e76c790d7f94d370fb59ec0a8b392c563ddc2/src/layer/tile/TileLayer.js#L163-L180) to trap the problematic requests and instead fetch a completely blank tile.

```js
if (/* zoom level is 1 and the horizontal tile isn't between 0 and 1 */)) {
    return 'http://downloads2.esri.com/support/TechArticles/blank256.png'
} else {
    return Util.template(this._url, Util.extend(data, this.options));
}
```

**Comment by jgravois** [comment] 2018-02-06 23:54
i pushed https://github.com/Esri/esri-leaflet/commit/35abd0b3a953c799cb5fa2b9c73497addb4eb87e to a branch called [`swapBlankTile`](https://github.com/Esri/esri-leaflet/tree/swapBlankTile) to make my suggestion a little clearer.

happy to chat more about it if it'd be helpful, but i'm going to close this issue in the meantime.

**Closed by jgravois** 2018-02-06 23:54 UTC

**Comment by IvannaBabchanik** [comment] 2018-02-08 07:38
Thank you for help. I'll take a look on the changes.

**Comment by DespertaWeb** [comment] 2019-07-30 14:59
> Thank you for help. I'll take a look on the changes.

How did you manged to solve this @IvannaBabchanik ??

**Comment by IvannaBabchanik** [comment] 2019-07-31 13:32
The issue was resolved
