### ISSUE TITLE
Layer refresh not removing unwanted markers

### ISSUE THREAD

**Issue by Greigrm** [Esri/esri-leaflet#665] opened 2015-10-23 20:43 UTC
My use case here may not be valid, so please close if not relevant.

I would like a layer where I can effectively leave the map screen open and have the layer re-queried in the background and any added markers placed onto the map, and any missing markers removed.  I'm not so concerned about changes to items staying on the map, just really the add/delete.

Looking at the disussion for #533 I have tried to use the featureLayer.refresh() method on a setTimeout, and while this adds new markers, it does not remove markers which are not in the result set.

To work around this I then tried simply calling the .setWhere() method (passing the existing where without change) and this works better and correctly removes deleted items, however if a popup is opened it will close when the setWhere() is triggered.

So I'm not sure if this is a bug report for refresh() not deleting markers, or a feature request for it to do the deletes.

**Comment by jgravois** [comment] 2015-10-23 23:29
`L.esri.featureLayer.refresh()` should definitely fetch newly created features *and* remove features from the map that are no longer present in the service.

I'll check into it.

**Comment by patrickarlt** [comment] 2015-10-28 03:50
@jgravois assigning to you. Take a look at how I did `setWhere` https://github.com/Esri/esri-leaflet/blob/master/src/Layers/FeatureLayer/FeatureManager.js#L180-L225.

The problem we are going to have is that right now `setWhere` destroys all the existing layers and then re-adds everything which is why the popup is closing when @Greigrm calls `setWhere` with the same where. It is definitely non-trivial to figure out that feature "X" is already active and does/doesn't need to be removed but you could definitely give it a shot.

**Comment by jgravois** [comment] 2015-10-28 03:51
:+1:

**Comment by gavinr** [comment] 2020-07-28 19:19
It looks like this is still an issue. Reproduction steps:

1. https://jsbin.com/kutivirogi/1/edit?html,output
2. Click on the map a few times to create some points.
3. Click "delete all" button
4. Click "refreshLayer" button
    - Expected: all points on the map disappear
    - Actual: all points stay there

**Comment by gavinr** [comment] 2020-08-06 15:50
This was fixed in [v2.5.0](https://github.com/Esri/esri-leaflet/releases/tag/v2.5.0).

**Closed by gavinr** 2020-08-06 15:50 UTC
