### ISSUE TITLE
map disappears when two-fingers zooming 

### ISSUE THREAD

**Issue by sunflo** [Esri/esri-leaflet#1296] opened 2021-10-12 06:39 UTC
hi,I used DynamicMapLayer to render raster tiles to use in the webview of Android System. When I use two-finger gestures to zoom in and out the map, the map disappears just after my finger touches the screen, and the map reappears after the new tiles are successfully loaded. When I narrowed the map layer to the full view I found that the map did not disappear when I touched the screen, but moved outside the screen. I found that this phenomenon should be the same problem as described in the issue #1085. Is this bug still there and still not fixed?Hope to receive ur response,thanks!!

btw,im using, esri-leaflet - v3.0.2

here is the video:
https://user-images.githubusercontent.com/5946151/136903946-4cbad48e-26dd-4aab-979b-73fdfdba9785.mp4

**Comment by sunflo** [comment] 2021-10-14 07:23
> Hi, thank you for the report. Does this happen on all environments (desktop browser, iOS, and Android) or just Android? Can you please post an example showing the issue (see "To Reproduce" section [here](https://github.com/Esri/esri-leaflet/blob/master/.github/ISSUE_TEMPLATE/bug_report.md))

Thanks for the reply, here is the the map demo, unzip it, install the apk in it and open the home page,the correct result is shown in the attached screenshot.  Not particularly sure if your network can access my map service.

Look forward to your reply,thanks again for  your help!!!

[app-debug.zip](https://github.com/Esri/esri-leaflet/files/7343819/app-debug.zip)
![device-2021-10-14-151750](https://user-images.githubusercontent.com/5946151/137269877-ce269ee3-bc58-4fac-be7d-f2a8536196dd.png)

**Comment by gavinr** [comment] 2021-10-14 12:53
Hi, I'm not able to install an APK. Does the issue happen if you load a webpage in the android web browser? Perhaps that might be a simpler replication case.

**Comment by sunflo** [comment] 2022-03-18 03:03
so , are you going to fix this problem?!!?

**Comment by sunflo** [comment] 2022-03-18 03:03
> Hi, I'm not able to install an APK. Does the issue happen if you load a webpage in the android web browser? Perhaps that might be a simpler replication case.

**Comment by gavinr** [comment] 2022-09-09 13:56
Hi, If you browse to https://developers.arcgis.com/esri-leaflet/samples/simple-feature-layer/ on your android phone, does the issue happen in the sample map that is embedded in that page?

**Comment by patrickarlt** [comment] 2022-09-13 20:28
@sunflo I can't reproduce this on my Android phone in the Chrome browser. Internally `DynamicMapLayer` just renders one or more [`ImageOverlay`](https://leafletjs.com/reference.html#imageoverlay) instances.

Does using a `ImagerOverlay` directly in Leaflet also have this same behavior? If so then this is likely a leaflet layer.

**Comment by sunflo** [comment] 2022-09-22 07:49
> @sunflo I can't reproduce this on my Android phone in the Chrome browser. Internally `DynamicMapLayer` just renders one or more [`ImageOverlay`](https://leafletjs.com/reference.html#imageoverlay) instances.
> 
> Does using a `ImagerOverlay` directly in Leaflet also have this same behavior? If so then this is likely a leaflet layer.

It seems not, until I integrated the arcgis plugin I didn't run into this problem. If you can you can visit the demo I mentioned before ===》》》https://github.com/Esri/esri-leaflet/issues/1296#issuecomment-944018445

**Comment by gavinr** [comment] 2022-11-08 18:09
Since there hasn't been much activity on this and it looks like the original demo is not working, I'm going to close this.

@sunflo if this is still an issue, please post a working demonstration case with step-by-step instructions on how to replicate the issue.

**Closed by gavinr** 2022-11-08 18:09 UTC
