### ISSUE TITLE
Basemap layers do not work in IE11

### ISSUE THREAD

**Issue by chriserickson** [Esri/esri-leaflet#481] opened 2015-03-13 20:46 UTC
The easiest way to test it is to try and visit your [examples site](http://esri.github.io/esri-leaflet/examples/) in IE11 -- the base maps won't load.

Executing 'new L.esri.BasemapLayer('Topographic')' from the console returns "Access is denied" from Request.js#123.

**Comment by jgravois** [comment] 2015-03-14 03:31
i can't reproduce what you're reporting on a Windows 7 VM running IE 11.0.9600.17633.

you're not having any trouble viewing esri basemaps using the [JSAPI](http://developers.arcgis.com/javascript/samples/widget_basemap/) in the same browser?

**Comment by chriserickson** [comment] 2015-03-16 14:43
The JSAPI site appears to load fine.

Here's a screenshot during the load of the examples site:
![image](https://cloud.githubusercontent.com/assets/1971519/6668436/8a384f2e-cbb8-11e4-8132-6d92f7ff1260.png)

**Comment by patrickarlt** [comment] 2015-03-16 16:29
This is really weird. IE 10+ supports CORs and Esri Leaflet has detected CORs support and used the appropriate request method to try to get the map attributions, this is where the failure is happening.

@chriserickson here are a thing you should try.

1. Add `L.esri.get = L.esri.Request.get.JSONP;` at the top of your code and see if it works. This will force Esri Leaflet to use JSONP even if it detects CORs support.
2. Can you double check that you aren't running IE in quirks mode or another browser mode?
3. Is this also broken in IE 9 and IE 10?

Googling for [access denied cors ie 11](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=access%20denied%20cors%20ie%2011&es_th=1) turns up a lot of https/http and localhost errors. I' wondering if switching to protocol relative URLs in https://github.com/Esri/esri-leaflet/blob/master/src/Layers/BasemapLayer.js would fix this?

@chriserickson is there any way you can test out switching to protocol relative URLs?

**Comment by chriserickson** [comment] 2015-03-17 15:59
Let me see if I can look at it today or tomorrow.

**Comment by chriserickson** [comment] 2015-03-25 15:19
Sorry for the delay. I should be getting to this by the first of next week.
Other priorities have been in the way.

**Comment by chriserickson** [comment] 2015-03-25 20:39
@patrickarlt, sorry for the long delay, but here is some additional info.

First off, this appears to be happening on the calls to get the attribution. 
`'https://static.arcgis.com/attribution/World_Topo_Map'`

I tried changing this to:
`tileProtocol + '//static.arcgis.com/attribution/World_Topo_Map'`

and am still seeing the same error.

As far as your other questions:
1. `L.esri.get = L.esri.Request.get.JSONP;' appears to make things work.
2. I verified I'm not in quirks mode
3. The emulation in IE 9/10 work just fine.

**Comment by jgravois** [comment] 2015-03-25 20:56
thanks @chriserickson
can anyone else reproduce this?

**Comment by chriserickson** [comment] 2015-03-25 20:57
We've had some users report it when testing our site on IE 11.

In both cases, we are on government computers/networks.

**Comment by patrickarlt** [comment] 2015-03-26 19:00
@chriserickson `L.esri.get = L.esri.Request.get.JSONP;` definitely narrows this to a CORs error. This [post](http://blog.algolia.com/jsonp-still-mandatory/) would seem to indicate that Cisco AnyConnect VPN and/or protocol mismatches would cause CORs failures.

The short term solution would be to use `L.esri.get = L.esri.Request.get.JSONP;` in your app.

Long term would be detecting CORs failures and automatically switching to JSONP. Could you run this in the dev tools on one of the problematic machines and tell me what the console output says?

```js
L.esri.Request.get.CORS('https://static.arcgis.com/attribution/World_Topo_Map', {
  // no params
}, function(e, r){
  console.log('error');
  console.log(e);
  console.log('response');
  console.log(r);
});
```

I want to see if I can create an automatic fallback to JSONP using the error message.

**Comment by chriserickson** [comment] 2015-04-17 14:55
Hi Patrick,
Sorry again for the slow response...

Here is the result I got when running that in IE11
![image](https://cloud.githubusercontent.com/assets/1971519/7204445/6fc3be72-e4df-11e4-84a6-2585bafc27c1.png)

**Comment by patrickarlt** [comment] 2015-04-18 14:48
Thanks for running that @chriserickson. It looks like this follows the same pattern as other CORS related errors where its uncatchable for security reasons. 

Adding `L.esri.get = L.esri.Request.get.JSONP;` is probably the way to go for now. I'm going to leave this open as a reminder to look into defaulting to JSONP no matter what and detecting CORS support automatically like the JS API for 1.0.

**Comment by patrickarlt** [comment] 2015-04-25 02:42
@chriserickson I've thought about this a bit now. Its going to be a very non-trivial thing to implement CORS detection that would catch this edge case. This would have to work like this.

1. Change everything to use JSONP by default
2. Whenever you create anything request the service metadata with a CORS request
3. If the CORS request for the metadata succeeds upgrade the service to use CORS rather then JSONP

The big problem comes down to what to do while you wait for the 3rd step. If a user immediately fires a POST request we cant accomplish that with JSONP so we would need to wait for the CORS request to succeed. If the request fails we would need to execute that callback with an error. If the user makes a GET request over 2000 characters (safest bet for IE 8) we would need to change it to a POST request and we are back in the same boat.

This is all a huge amount of non-trivial low level code just to catch the case where the browser supports CORS but it is being blocked by a middleman. Also since most browsers will soon support CORS and ArcGIS Server 10.0 will retire on January 1st which means that CORS support will now be on by default for every supported version of server.

There are 2 options for making this a little easier on people.

1. Always use `L.esri.Request.get.JSONP` to request the attributions. This will pretty much always succeed.
2. Keep using `L.esri.get` and catch and log error and surface a warning in the console.

I'm more in favor of option 1 which will simply lead to more success.

**Comment by chriserickson** [comment] 2015-04-27 15:04
Do you perceive any downsides to always using JSONP for attributions?

**Comment by jgravois** [comment] 2015-04-27 17:08
just jumping back in uninvited :) ...

i guess it'd be nice to leverage the inherent CORS support defined in the HTML5 spec, but wrapping responses in a JSON callback doesn't have an inherent performance implication, so its a perfectly reasonable workaround in your situation.

**Comment by patrickarlt** [comment] 2015-04-27 19:23
I'm having a renewed interest in fixing this after another email from another user which might suggest this is more widespread.

> I’m putting together an application using esri-leaflet.js. It’s pretty much done but management has asked that I get everything running properly on IE 11. I’m getting some critical ‘Access is denied’ errors in Request.js in the following block of code:
>   
>        if(requestLength <= 2000 && L.esri.Support.CORS){
>           httpRequest.open('GET', url + '?' + paramString);
>           X Access is denied
>           httpRequest.send(null);
>        }
>   
> Do you know what I can do to resolve this error? 

----

@jgravois @chriserickson I'm starting to think this is one of two things:

* Related to hardcoding `https` as the protocol for the attribution URLs
* Related to some kind of weird security zones setting on Windows

@chriserickson I have a few more ideas to narrow this down since I still can't reproduce.

Could you try running the following and see if it works? Can you also make sure you are running this on a real web server and not a `file:` protocol (i.e. just opening up an HTML file). If you are using a real web server and are using `localhost` and you try this on both `localhost` AND `127.0.0.1`.

```js
var protocol = (window.location.protocol !== 'https:') ? 'http:' : 'https:';
L.esri.Request.get.CORS(protocol + '//static.arcgis.com/attribution/World_Topo_Map', {
  // no params
}, function(e, r){
  console.log('error');
  console.log(e);
  console.log('response');
  console.log(r);
});
```

Can you also try running the following sample using the ArcGIS API for Javascript on `localhost` and on `127.0.0.0` https://developers.arcgis.com/javascript/jssamples/map_simple.html?

Can you also confirm what the security settings for you windows machine are? If they are set to "High" we might have a problem because both the JS API and Esri Leaflet won't work over a CDN (at all) then.

Can you navigate to http://static.arcgis.com/attribution/World_Street_Map&f=json and https://static.arcgis.com/attribution/World_Street_Map&f=json In your browser normally?

And finally does the rest of your application work fine if you replace the `L.esri.BasemapLayer` with just a regular tile layer?

```js
L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
}).addTo(map);
```

**Comment by patrickarlt** [comment] 2015-04-28 15:23
@chriserickson After working with the user who also submitted this bug he found that the page was loading in IE 7 mode be default which would explain all the missing/broken functionality. It looks like we should force `edge` rendering on every page. Adding this might help resolve the problem.

```html
<meta http-equiv="x-ua-compatible" content="ie=edge">
```

In any case it solved it for him so I'm going to add this to every sample code page now.

**Comment by patrickarlt** [comment] 2015-04-29 19:20
@chriserickson According to this https://msdn.microsoft.com/en-us/library/ff405803%28v=vs.85%29.aspx  several things can fore IE to drop down to a lower document mode.

* Local Compatibility Site list
* Microsoft Compatibility Site list 
* Enterprise Mode IE Compatibility Site list
* Group Policy settings

Since you mentioned that this seemed specific to some government computers I'm willing to bet that one of those things forced the document to drop down and broke everything.

I'm going to add that `meta` tag to every sample to prevent this from happening and close this issue.

@chriserickson if you try this and it fails to resolve the problem reopen this and we can keep looking for a solution.

**Comment by chriserickson** [comment] 2015-04-29 19:37
Patrick,
We have that meta tag already, we also set it in a response header...

You can see it here (although we have the JSONP patch included as well)
http://ecos-beta.fws.gov/ipac2/gettingStarted/map

**Comment by patrickarlt** [comment] 2015-04-29 22:47
Thanks for the link. I did a little more digging In general everything worked fine for me. Attribution just doesn't show up period. The request is successful. (since you have the JSONP override in place) but both of the debugging snippets I posted above worked for me as well.

@chriserickson If you ignore the attribution error does the rest of the application function fine? I'm leaning toward just using JSONP for the attributions. If CORS is blocked then you will need to also need to use `useCors: false` on other layers.

**Comment by patrickarlt** [comment] 2015-05-01 18:16
@chriserickson @jgravois Since I'm fresh out of ideas I'm going to change this a JSONP request by default for the next release so this can be closed.

The ONLY impact this might have is that if CORS is blocked by a firewall/proxy/whatever you might not notice it until you start consuming non-basemap services. At this point you will have to `{useCors: false}` when using your services.

**Closed by patrickarlt** 2015-05-01 18:16 UTC
