### ISSUE TITLE
how to overlay multiple tile layers with different starting origin ?

### ISSUE THREAD

**Issue by ReneeLai** [Esri/esri-leaflet#629] opened 2015-09-08 05:47 UTC
if there's a way to overlay multiple tile layers with different starting origin .
![2](https://cloud.githubusercontent.com/assets/8597127/9727284/e2834db2-562f-11e5-8f4e-473a8101d56e.png)
![1](https://cloud.githubusercontent.com/assets/8597127/9727285/e289ccdc-562f-11e5-8296-eca400db9740.png)

**Comment by jgravois** [comment] 2015-09-08 14:56
duplicate of #630

**Closed by jgravois** 2015-09-08 14:56 UTC
