### ISSUE TITLE
How to difine the input parameters of GPRecordSet?

### ISSUE THREAD

**Issue by Giserwu** [Esri/esri-leaflet#1034] opened 2017-12-27 07:49 UTC
Hello there!
I would like to consult when using the esri-leaflet to call the GP service when the parameter format is GPFeatureRecordSetLayer can be defined as GeoJSON, but when the parameter format is GPRecordSet, how to define the input parameters? Can you give me a complete example of several different parameter calls? Thank you!
![qq 20171227154409](https://user-images.githubusercontent.com/23161877/34374704-5c805e64-eb1d-11e7-897c-5e8479603602.jpg)
@jgravois @ajturner

**Comment by jgravois** [comment] 2017-12-28 14:58
duplicate of https://github.com/jgravois/esri-leaflet-gp/issues/43

**Closed by jgravois** 2017-12-28 14:58 UTC
