### ISSUE TITLE
use  L.esri.query mesthods query two times ,the last show 'code: 400, message: Unable to complete operation.'

### ISSUE THREAD

**Issue by panshun** [Esri/esri-leaflet#1280] opened 2021-07-06 08:31 UTC
## Expected behavior

- Describe what you expected or wanted to happen.
- What you are trying to achieve?

## Actual behavior

- Describe what occurs in your code.
- Specifically, what seems to work differently than you intended?
- Provide any error messages you see in the console.
- If possible, create a [jsbin](http://jsbin.com/dagilag/edit?html,output) that demonstrates the problem.

## To Reproduce

Please share the steps to reproduce the behavior.

## Environment Information

- Version of Leaflet (`L.version`):
- Version of Esri Leaflet (`L.esri.VERSION`):
- Your OS: [e.g. iOS]
- Browser and Version [e.g. chrome 80.0, safari 12.1.1]

## Additional context

Add any other context about the problem here. If you're are *not* using the [CDN](http://www.jsdelivr.com/projects/leaflet.esri), please note what loading/bundling library you are using ([webpack](https://webpack.github.io/), [browserify](http://browserify.org/), [RequireJS](http://requirejs.org/))?

**Comment by gavinr** [comment] 2021-07-07 01:40
@panshun Closing this issue because there are no details on the report - this is our default issue template. If this was in error, please open a new issue, fill out the details (expected behavior, actual behavior, screenshots, etc)

**Closed by gavinr** 2021-07-07 01:40 UTC
