### ISSUE TITLE
isModern being toggled when making featureLayer requests

### ISSUE THREAD

**Issue by alukach** [Esri/esri-leaflet#1114] opened 2018-07-24 21:18 UTC
* Browser and version:

Chrome 67

* Version of Leaflet (`L.version`):

`1.3.3`

* Version of esri Leaflet (`L.esri.VERSION`):

`2.2.`

Steps to reproduce the error:

I am putting together a webmap via `leaflet`, `esri-leaflet`, and `react-leaflet` in a fashion similar to that demonstrated in [this (very helpful) example](https://github.com/jgravois/react-leaflet/blob/esri-sample/example/components/esri.js).

I've noticed that, when adding a `featureLayer` to my map, the library makes 2 requests to my feature layer.  The requests are something along the lines of:

1. `/query?returnGeometry=true&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-180%2C%22ymin%22%3A-89.99075251648904%2C%22xmax%22%3A-179.9999999999999%2C%22ymax%22%3A85.0511287798066%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=json`
2. `/query?returnGeometry=true&where=1%3D1&outSr=4326&outFields=*&inSr=4326&geometry=%7B%22xmin%22%3A-180%2C%22ymin%22%3A-85.0511287798066%2C%22xmax%22%3A180%2C%22ymax%22%3A85.0511287798066%2C%22spatialReference%22%3A%7B%22wkid%22%3A4326%7D%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&geometryPrecision=6&f=geojson`

Notice that the first request ends with `f=json` and the second ends with `f=geojson`.  This causes the first set of geometry to come back in its native spatial reference of `3857`, which the second comes in `4326`.

I have been able reproduce this with the public MapServer `https://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer/0`.  You can see an example of the error (by analyzing the network requests) here: https://l9x040wj1q.codesandbox.io/ (code here: https://codesandbox.io/s/l9x040wj1q).  Both my service and this service are in `3857`.

Dropping a debugger on https://github.com/Esri/esri-leaflet/blob/f0378e2db19b5326d70ac535b49eddd3bae53304/src/Tasks/Query.js#L129 allows me to see that `this.options.isModern` changes from `undefined` to `true` between the first and second request.  I'm guessing that is caused by this line: https://github.com/Esri/esri-leaflet/blob/b823548f9e3b0a459d47c6c1f5cf30e0a38a6ed4/src/Layers/FeatureLayer/FeatureManager.js#L80-L83

It's possible that I'm not understanding what's happening and the two requests _should_ be in different formats (perhaps they serve a different purpose).  When rubber hits the road, this issue causes my features to sometimes appear on the map, and other times not (my guess is that it's a race condition based on which returns a response first).

Setting `isModern: true` avoids this issue entirely.

**Comment by jgravois** [comment] 2018-07-27 17:30
> This causes the first set of geometry to come back in its native spatial reference of 3857, which the second comes in 4326.

if you take a closer look at your example queries, you'll see that they _both_ contain `outSR=4326` so they both _should_ return long/lat coordinates.

> Notice that the first request ends with `f=json` and the second ends with `f=geojson`

this is definitely _by design_. we have to make an AJAX request to check whether or not `f=geojson` is supported by an arbitrary service. we don't want to delay firing off gridded queries until after the response comes back. our goal is to _gracefully_ upgrade and stop parsing internally without the client app being able to tell the difference.

i don't remember anyone else reporting a race condition that caused features to fail to display, but if you know the service in question supports `f=geojson` as an output format, setting `isModern` is definitely an appropriate move.

**Comment by jgravois** [comment] 2018-07-31 15:10
closing, but happy to chat more if anyone has further questions down the road.

**Closed by jgravois** 2018-07-31 15:10 UTC
