### ISSUE TITLE
L.tileLayer.wms vs L.esri.dynamicMapLayer layer index

### ISSUE THREAD

**Issue by defineconst** [Esri/esri-leaflet#1129] opened 2018-10-25 13:21 UTC
I have two layers , L.tileLayer.wms and L.esri.dynamicMapLayer,I want to use L.esri.dynamicMapLayer as base layer , then put L.tileLayer.wms layer on it.
but L.tileLayer.wms layer on the bottom,L.esri.dynamicMapLayer on the top.
How I can resolve it.
thank you very much.

**Comment by jgravois** [comment] 2018-10-25 13:38
the appropriate way to get control over the draw order of layers in a Leaflet app is [map panes](http://esri.github.io/esri-leaflet/examples/layer-ordering.html)

https://leafletjs.com/reference-1.3.4.html#tilelayer-wms-pane
http://esri.github.io/esri-leaflet/api-reference/layers/dynamic-map-layer.html#options

**Comment by jgravois** [comment] 2018-10-25 17:15
closing as a duplicate of #739, #753, #923, #1000, #1073

**Closed by jgravois** 2018-10-25 17:15 UTC
