### ISSUE TITLE
Updating a Feature Layer with useCors: false causes syntax error for some services

### ISSUE THREAD

**Issue by ahalota** [Esri/esri-leaflet#1064] opened 2018-03-09 20:13 UTC
I've seen this issue only show up with the layer published below. Did not get the same issue with the marker feature layer shown in the polygon. (Sorry, tried and failed to set up a jsfiddle for this...pasted below my whole sample code.

If you plug this on and set up the console. Click 'toggle layer', and it adds the feature layer just fine. Removing its ok, but when it gets re-added it shows this error in the console:

> Uncaught SyntaxError: Unexpected token :

What is this error related to? It seems to get the response just fine, but after initially removing a layer I am not able to re-add it again. This happens only with the option useCors: false.

EDIT: This also happens when I am moving around the map once I have added the layer. Basically the request that is sent out to get the data gives back that error (it's usually several logs on the console at once, I assume a few requests are sent out to grab the data for each subset of the area)
```
<html>
<head>
  <meta charset=utf-8 />
  <title>Simple FeatureLayer</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

    <!-- Load Leaflet from CDN -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
    integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
    integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
    crossorigin=""></script>


    <!-- Load Esri Leaflet from CDN -->
    <script src="https://unpkg.com/esri-leaflet@2.1.3/dist/esri-leaflet.js"
    integrity="sha512-pijLQd2FbV/7+Jwa86Mk3ACxnasfIMzJRrIlVQsuPKPCfUBCDMDUoLiBQRg7dAQY6D1rkmCcR8286hVTn/wlIg=="
    crossorigin=""></script>


  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:20; bottom:0; right:0; left:0; }
  </style>
</head>
<body>

<button id="button" onclick="toggleLayer()">Toggle feature Layer</button>
<div id="map">
</div>

<script>
  var map = L.map('map').setView([18.24, -66.41],10);

  L.esri.basemapLayer('Streets').addTo(map);
  var fl = L.esri.featureLayer({
    url: 'https://maps.nccs.nasa.gov/server/rest/services/gliht/201703_PuertoRico_test/MapServer/16',
    useCors: false
  });
  
  function toggleLayer(){
	  if (map.hasLayer(fl)){
		  console.log('removing feature layer');
		  map.removeLayer(fl);
		  console.log('removed feature layer');
	  } else {
		  console.log('adding feature layer');
		  map.addLayer(fl);
		  console.log('added featue layer');
	  }
  }
  
  
</script>

</body>
</html>
```

**Comment by kragoth** [comment] 2018-03-19 04:44
@ahalota I am also getting this error. However, I get some success if I set the isModern flag to false when adding the feature layer. 
Unfortunately, this seems to have another very problematic bug. Not all features will render. In fact, very few features seem to render for me.
I'm at a bit of a loss on this one at the moment.

Anyway, I've created a [jsbin ](http://jsbin.com/hojorijuya/edit?html,output)with your code and added the isModern: false so you can see what happens.

**Comment by jgravois** [comment] 2018-03-22 04:53
why are you setting `useCors: false`? your service [supports it](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fmaps.nccs.nasa.gov%2Fserver%2Frest%2Fservices%2Fgliht%2F201703_PuertoRico_test%2FMapServer%2F16&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote).

either way, you found a [JSONP](https://en.wikipedia.org/wiki/JSONP) bug in ArcGIS Server that only affects `geojson` output.

https://maps.nccs.nasa.gov/server/rest/services/gliht/201703_PuertoRico_test/MapServer/16/query?where=1=1&f=json&callback=myCallback
```js
myCallback({
  // ...
  "features": [
    // ...
  ]
});
```
https://maps.nccs.nasa.gov/server/rest/services/gliht/201703_PuertoRico_test/MapServer/16/query?where=1=1&f=geojson&callback=myCallback
```js
// response NOT wrapped in a callback
{
  "type": "FeatureCollection",
  "features": [
    // ...
  ]
}
```
the error is reproducible in [10.6](http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3/query?where=STATE_NAME=%27Hawaii%27&returnGeometry=false&f=geojson&callback=foo), but not in [ArcGIS Online](https://services.arcgis.com/EDxZDh4HqQ1a9KvA/arcgis/rest/services/retail_sites/FeatureServer/0/query?where=1%3D1&returnGeometry=false&f=geojson&callback=foo) hosted feature services

the reason you don't see the problem in Esri Leaflet immediately is that we use `f=json` until we're able to make a metadata request to confirm support for native geojson in the service.

**Comment by garymd210** [comment] 2018-03-22 15:17
Yes – will forward / discuss  with the server ddevs

**Comment by ahalota** [comment] 2018-03-22 16:33
At the time it hadn't allowed CORS from my host, the admin changed it for me, so I enabled it after that and just ignored the issue.

**Comment by jgravois** [comment] 2018-03-22 16:50
thx @garymd210!

**Comment by jgravois** [comment] 2018-03-30 21:32
not much more we can do in esri-leaflet. closing.

**Closed by jgravois** 2018-03-30 21:32 UTC
